### PR TITLE
Try index on racer fail

### PR DESCRIPTION
**Pull request by Woyten**
I played around with the new index. Turned out that some new cool things can be done using it!

One of those things on my agenda was to fix the problem that Racer often does not find any result, e.g. because an element is not visible from the root of the source tree. This PR solves most of the issues related to that problem.

Content of this PR:
- If Racer fails to find a definition the corresponding element is searched using the index instead.
- If there is more than one result the user can pick the desired location.
- The index now outputs the location and not the type signature any more.
- The index matching performance has been improved.

This PR is quite big as it builds up on my Open_Type branch which is not merged yet.

### CODE REVIEW

**Comment by Woyten** [comment]
By the way, can we add Mockito as testing framework? It is hardly possible to test anything that uses the interfaces of the `org.eclipse.ui` package.

**Comment by Woyten** [comment]
@bruno-medeiros Sorry to bother you again but it would be great if you could give some notes on the spirit of contributing to RustDT as it is not evident to me.

Is RustDT a collaborative project of everyone who has the motivation to contribute to it, s.t. it can evolve quickly to a fully featured and productive IDE? If so, then it would be helpful to get sooner feedback about pull request/review statuses, code style, programming errors and the like - hopefully resulting in fruitful discussions. We should keep in mind that programming is a social process and the worst thing that can happen is that opportunities are missed just because people did not talk.

Currently, it feels to me as if RustDT is more a project of a single person and a very small elite of selected insiders while external contributions are met with scepticism. Maybe even unwelcome? Probably, I am plain wrong about that. However, I am asking because I know that many projects share a spirit where contributors are considered as competitors, a thing that I never understood as contributors usually strive for the same goal.

In any way, whether RustDT is a collaborative project or a one-man-show, it would be fair for all contributors to have a clear statement which and whose contributions are desired or not.

I will probably continue to work on other index-based features that I will find to be missing. But keeping my repo up-to-date with yours will become increasingly harder. My solution: Let's make Rust successful by bringing our features together and further improving RustDT!

Cheers,
Woyten

**Comment by bruno-medeiros** [comment]
@Woyten Sorry for these big delays in coming back with a reply, that was bad form on my part. I have been super busy in the last weeks, and held back from replying in part because I could see it was a big PR to review. So that mostly the only thing I could have said earlier is "I still don't have time to review it". I haven't even touched Eclipse code in the last weeks, other than few very minor fixes/changes - my attention has been devoted to working on https://github.com/RustDT/RustLSP and more recently few related PRs to https://github.com/jonathandturner/rls/

BTW, you have seen the announcement of the Rust Language Server, yes? (https://internals.rust-lang.org/t/introducing-rust-language-server-source-release/4209) It's all very recent, but it changes a few things on how to approach IDE development.

To clarify, contributions are welcome, but that doesn't mean _all_ contributions are welcome. They still should have a certain standard of quality (in implementation), and be of usefulness to the user. Of course, when contributions are not suitable, that should be communicated clearly to whoever contributed, so that he/she can make changes, or possibly abandon the contributions altogether (or at least know why it wasn't accepted). There has recently been one medium-sized PR accepted with relative quickness and just a few iterations : https://github.com/RustDT/RustDT/pull/137

As for this PR, I'm afraid the news doesn't look too good. I haven't looked at the code itself, but the problem here is the offered functionality is very limited and soon to be made obsolete by work on RLS. The RLS uses not only Racer but also rustc compiler itself, so it can be much more precise. If anything, if you have ideas on how to use an index to make completions more precise, it might make more sense to add that functionality to RLS itself. 

Let me ask:, does this functionality even work with references to symbols to a dependency crate that is not in Eclipse workspace? (I guess that depends on how the index works)

As a general tip, if you are a new contributor to a project, it's best to start with smaller PRs than big ones straight away, or at least ask the developers first if is a feature they would be interested in including in the project before you start work on it, because otherwise you risk there not being interest in accepting the contribution, regardless of the quality of implementation. I've been there myself, made that mistake with submitting a big patch for Eclipse Platform (asynchronous auto-save), which now I realize has almost zero chance of being accepted, simply because there is no interest in the feature itself and having it reviewed.

**Comment by Woyten** [comment]
@bruno-medeiros Thank you very much for your reply! I'm glad to hear that contributions, in general, are welcome and the slow communication is only a matter of available time. It's also good to know, that, apparently, I am  not the only person with PRs that start to grow exponentially...

To answer to your first question: Yes, I heard about the Rust Language Server and I have a high-level understanding of it. I totally agree that a compiler-driven language server is the best and most straightforward way to implement seamless IDE support. So, it's clear that, in a year, RustDT will look completely different to what it looks now. Is RustDT even needed then or will a general-purpose LSP client plugin do the job?

To my knowledge, the current langue server implementation is still in an early stage and it uses Racer under the hood. As indexing is a too important feature of every IDE and Racer has too many limitations, I decided not to wait and implemented the indexing by myself instead. Since then, I profit significantly from it every day. Even if the index will become obsolete soon, people could benefit from it right now (you get it for quasi for free) and the index can be removed once the language server is good enough. So, even if my code is extraordinarily bad: It will not last forever. ;-)

Regarding your second question: The indexing mechanism scans every .rs file in every project folder. As cargo puts copies of every dependency in the `./target` folder of the corresponding project, those dependencies can be found without any problem. I think the Java indexing works more or less in the same way. It is not able find anything outsinde the current workspace except if it is referenced explicitly by some Maven or Ivy plugin. Another point to mention is that the rustc src folder currently is not part of the index. It did not work on that as it was not important to me and I did not want to increase the PR size even more. However, it would be easy to fix this.

**Comment by bruno-medeiros** [comment]
> So, it's clear that, in a year, RustDT will look completely different to what it looks now. Is RustDT even needed then or will a general-purpose LSP client plugin do the job?

There will still definitely be a need for RustDT, since there are some parts of functionality that are not covered by the LSP protocol. But the code size of RustDT might reduce a lot, as code that is now part of RustDT/Melnorme gets moved or made obsolete by a general LSP library. There is already work being done in that for Eclipse: https://github.com/eclipselabs/eclipse-language-service.
In particular this PR was added just 3 days ago to support the Open Symbols functionality: https://github.com/eclipselabs/eclipse-language-service/pull/77

> Regarding your second question: The indexing mechanism scans every .rs file in every project folder. As cargo puts copies of every dependency in the ./target folder of the corresponding project, those dependencies can be found without any problem.

It only puts copies of the .rlib file of the dependency, but not the source files. Source is only there for the few projects that use source generation in the Cargo build script (and even so that is a source that actually we don't want to index because the user can't edit it anyways).

**Comment by bruno-medeiros** [comment]
I'm going to close this pull request, see the feedback above. (apologies for not giving feedback earlier)

**Pull request closed without merging**
