### PR TITLE
Add numbers syntax highlighting support for Rust editor

### PR DESCRIPTION
**Pull request by Koka**
Hi Bruno!

I've found an issue #55 is still Open, so I've added some improvements to rust editor syntax coloring that are related to number literals - just to practice in eclipse plugin programming.

You could merge it into RustDT if you'll find my changes useful.

Thank you for your great rust eclipse plugin!

### CODE REVIEW

**Comment by bruno-medeiros** [comment]
I'm going on holidays this weekend, so I'll have a look after I get back.

**Comment by bruno-medeiros** [comment]
There's a few bugs, mostly not checking for EOF when calling lookahead() 

Add this test to the PR, to fix such bugs:
(it would also be cool if you could expand the test cases too: test the float suffixes, the binary/octal/hex literals, etc.)

```
/*******************************************************************************
 * Copyright (c) 2015 Bruno Medeiros and other Contributors.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Bruno Medeiros - initial API and implementation
 *******************************************************************************/
package com.github.rustdt.tooling.lexer;

import static melnorme.utilbox.core.Assert.AssertNamespace.assertTrue;

import org.junit.Test;

import melnorme.lang.tooling.parser.lexer.StringCharacterReader;

public class LexingRulesTest {

    public static void testRule(RustNumberLexingRule lexRule, String source, int expectedTokenLength) {
        StringCharacterReader reader = new StringCharacterReader(source);
        boolean isMatch = lexRule.evaluate(reader);

        assertTrue(isMatch == (expectedTokenLength > 0));
        assertTrue(reader.getOffset() == expectedTokenLength);
    }

    public static void testNumberRule(String source, int expectedTokenLength) {
        testRule(new RustNumberLexingRule(), source, expectedTokenLength);
    }

    @Test
    public void testNumberLexingRule() throws Exception { testNumberLexingRule$(); }
    public void testNumberLexingRule$() throws Exception {
        testNumberRule("123", 3);
        testNumberRule("xxx", 0);
        testNumberRule("", 0);
        testNumberRule("123xxx", 3);
        testNumberRule("123.4xxx", 5);
    }

}
```

**Comment by Koka** [comment]
Updated pull request with expanded version of your test. It's passing now, but I had to change StringCharacterReader to prevent exceptions on lookahead() calls when offset is negative because I haven't found any good way (using current implementation of StringCharacterReader) to check if reader underflow happened.

**Comment by bruno-medeiros** [comment]
Well, I merged it in, but with some changes. FYI:

First, you can't change StringCharacterReader the way you did. The contract of ICharacterReader means you can only call unread() the same number of times as read(), so it's not allowed to bring the reader into underflow in the first place. Although StringCharacterReader could be modified to allow that scenario, the other ICharacterReader implementation (CharacterScannerHelper) can't. 

Also fixed a few minor bugs, like the minus sign being parsed after the literal prefix, or "123." not being accepted.

**Pull request merged**
